Pkg.add("JSON")
Pkg.add("DataStructures")
Pkg.clone("https://github.com/TotalVerb/EnglishText.jl")
Pkg.clone("https://github.com/TotalVerb/SExpressions.jl")
Pkg.clone("https://github.com/TotalVerb/Remarkable.jl")
