Pkg.add("JSON")
Pkg.add("DataStructures")
Pkg.add("EnglishText")
Pkg.add("Glob")
Pkg.clone("https://github.com/TotalVerb/SExpressions.jl")
Pkg.clone("https://github.com/TotalVerb/SchemeSyntax.jl")
Pkg.clone("https://github.com/TotalVerb/Remarkable.jl")
